In [1]:
# Dependencies and setup
import pandas as pd
import numpy as np

# Load data file
raw_data_SAT = "GOSA_SAT_highest_2018.csv"

# Read School and Student data files and store them each into Pandas DataFrames
data_SAT = pd.read_csv(raw_data_SAT)

data_SAT.head()

,LONG_SCHOOL_YEAR,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,INSTN_NUMBER,INSTN_NAME,SUBGRP_DESC,TEST_CMPNT_TYP_CD,NATIONAL_NUM_TESTED_CNT,STATE_NUM_TESTED_CNT,DSTRCT_NUM_TESTED_CNT,INSTN_NUM_TESTED_CNT,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL,INSTN_AVG_SCORE_VAL
0,2017-18,601,Appling County,103,Appling County High School,All Students,Combined Test Score,2136539,65795,102.0,102.0,1052,1020.0,1020.0
1,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Analysis Score - New,1449142,28569,29.0,29.0,4,3.0,3.0
2,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Reading Score - New,1449142,28569,29.0,29.0,5,5.0,5.0
3,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Total,1449142,28569,29.0,29.0,13,12.0,12.0
4,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Writing Score - New,1449142,28569,29.0,29.0,5,5.0,5.0

In [17]:
# Quickly review all district names. Do they all have "county" in them?
data_SAT["SCHOOL_DSTRCT_NM"].unique()

array(['Appling County', 'Atkinson County', 'Bacon County',
       'Baker County', 'Baldwin County', 'Banks County', 'Barrow County',
       'Bartow County', 'Ben Hill County', 'Berrien County',
       'Bibb County', 'Bleckley County', 'Brantley County',
       'Brooks County', 'Bryan County', 'Bulloch County', 'Burke County',
       'Butts County', 'Calhoun County', 'Camden County',
       'Candler County', 'Carroll County', 'Catoosa County',
       'Charlton County', 'Savannah-Chatham County',
       'Chattahoochee County', 'Chattooga County', 'Cherokee County',
       'Clarke County', 'Clayton County', 'Clinch County', 'Cobb County',
       'Coffee County', 'Colquitt County', 'Columbia County',
       'Cook County', 'Coweta County', 'Crawford County', 'Crisp County',
       'Dade County', 'Dawson County', 'Decatur County', 'DeKalb County',
       'Dodge County', 'Dooly County', 'Dougherty County',
       'Douglas County', 'Early County', 'Echols County',
       'Effingham County', 'Elbert County', 'Emanuel County',
       'Evans County', 'Fannin County', 'Fayette County', 'Floyd County',
       'Forsyth County', 'Franklin County', 'Fulton County',
       'Gilmer County', 'Glascock County', 'Glynn County',
       'Gordon County', 'Grady County', 'Greene County',
       'Gwinnett County', 'Habersham County', 'Hall County',
       'Hancock County', 'Haralson County', 'Harris County',
       'Hart County', 'Heard County', 'Henry County', 'Houston County',
       'Irwin County', 'Jackson County', 'Jasper County',
       'Jeff Davis County', 'Jefferson County', 'Jenkins County',
       'Johnson County', 'Jones County', 'Lamar County', 'Lanier County',
       'Laurens County', 'Lee County', 'Liberty County', 'Lincoln County',
       'Long County', 'Lowndes County', 'Lumpkin County', 'Macon County',
       'Madison County', 'Marion County', 'McDuffie County',
       'McIntosh County', 'Meriwether County', 'Miller County',
       'Mitchell County', 'Monroe County', 'Montgomery County',
       'Morgan County', 'Murray County', 'Muscogee County',
       'Newton County', 'Oconee County', 'Oglethorpe County',
       'Paulding County', 'Peach County', 'Pickens County',
       'Pierce County', 'Pike County', 'Polk County', 'Pulaski County',
       'Putnam County', 'Quitman County', 'Rabun County',
       'Randolph County', 'Richmond County', 'Rockdale County',
       'Schley County', 'Screven County', 'Seminole County',
       'Griffin-Spalding County', 'Stephens County', 'Stewart County',
       'Sumter County', 'Talbot County', 'Taliaferro County',
       'Tattnall County', 'Taylor County', 'Telfair County',
       'Terrell County', 'Thomas County', 'Tift County', 'Toombs County',
       'Towns County', 'Treutlen County', 'Troup County', 'Turner County',
       'Twiggs County', 'Union County', 'Thomaston-Upson County',
       'Walker County', 'Walton County', 'Ware County', 'Warren County',
       'Washington County', 'Wayne County', 'Webster County',
       'Wheeler County', 'White County', 'Whitfield County',
       'Wilcox County', 'Wilkes County', 'Wilkinson County',
       'Worth County', 'Atlanta Public Schools', 'Bremen City',
       'Buford City', 'Calhoun City', 'Carrollton City',
       'Cartersville City', 'Chickamauga City', 'Commerce City',
       'Dalton Public Schools', 'Decatur City', 'Dublin City',
       'Gainesville City', 'Jefferson City', 'Marietta City',
       'State Charter Schools- Mountain Education Center School',
       'State Charter Schools- Provost Academy Georgia',
       'State Charter Schools- Georgia Connections Academy',
       'State Charter Schools- Foothills Charter High School (Madison Campus)',
       'Commission Charter Schools- CCAT School',
       'Commission Charter Schools- Fulton Leadership Academy',
       'Pelham City', 'Rome City', 'Social Circle City',
       'Thomasville City', 'Trion City', 'Valdosta City', 'Vidalia City',
       'State Schools- Georgia Academy for the Blind'], dtype=object)

In [18]:
# Quickly review all school names. Are they all GA High Schools?
data_SAT["INSTN_NAME"].unique()

array(['Appling County High School', 'Atkinson County High School',
       'Bacon County High School', 'Baker County K12 School',
       'Baldwin High School', 'Banks County High School',
       'Apalachee High School', 'Winder-Barrow High School',
       'Adairsville High School', 'Cass High School',
       'Woodland High School', 'Fitzgerald High School',
       'Berrien High School',
       'Berrien Academy Performance Learning Center',
       'Howard High School', 'Central High School',
       'Westside High School', 'Rutland High School',
       'Northeast High School', 'Southwest High School',
       'Bleckley County High School', 'Brantley County High School',
       'Brooks County High School', 'Richmond Hill High School',
       'Bryan County High School', 'Southeast Bulloch High School',
       'Statesboro High School', 'Portal Middle/High School',
       'Burke County High School', 'Jackson High School',
       'Calhoun County High School', 'Camden County High School',
       'Metter High School', 'Temple High School', 'Mt. Zion High School',
       'Bowdon High School', 'Villa Rica High School',
       'Heritage High School', 'Lakeview-Fort Oglethorpe High School',
       'Ringgold High School', 'Charlton County High School',
       'Johnson High School', 'Early College Program',
       'Woodville-Tompkins Technical and Career High School',
       'New Hampstead High School',
       'The School of Liberal Studies at Savannah High',
       'Islands High School', 'Savannah Arts Academy',
       'Beach High School', 'Groves High School', 'Jenkins High School',
       'Windsor Forest High School', 'Chattahoochee County High School',
       'Chattooga High School', 'Creekview High School',
       'River Ridge High School', 'Etowah High School',
       'Sequoyah High School', 'Polaris Evening School',
       'Woodstock High School', 'Cherokee High School',
       'Tippens Educational Center', 'Cedar Shoals High School',
       'Classic City High School', 'Clarke Central High School',
       "Mundy's Mill High School", 'Elite Scholars Academy School',
       'Charles R. Drew High School', 'Lovejoy High School',
       'Martha Ellen Stilwell School for the Performing Arts',
       'Mount Zion High School', 'Riverdale High School',
       'Forest Park High School', 'Jonesboro High School',
       'North Clayton High School', 'Morrow High School',
       'Clayton County Open Campus/Career Academy',
       'Clayton County Alternative Center', 'Clinch County High School',
       'Kennesaw Mountain High School', 'Kell High School',
       'Walton High School', 'Oakwood Digital Academy',
       'Pope High School', 'Harrison High School',
       'Allatoona High School', 'Sprayberry High School',
       'Lassiter High School', 'Hillgrove High School',
       'Campbell High School', 'McEachern High School',
       'Wheeler High School', 'North Cobb High School',
       'Osborne High School', 'South Cobb High School',
       'Pebblebrook High School',
       'Wiregrass Regional College and Career Academy',
       'Coffee County High School',
       'George Washington Carver Freshman Campus',
       'Colquitt County High School', 'Grovetown High School',
       'Harlem High School', 'Lakeside High School',
       'Greenbrier High School', 'Evans High School', 'Cook High School',
       'Northgate High School', 'East Coweta High School',
       'Newnan High School', 'Crawford County High School',
       'Crisp County High School', 'Dade County High School',
       'Dawson County High School', 'Bainbridge High School',
       'Martin Luther King, Jr. High School', 'Miller Grove High School',
       'Destiny Achievers Academy of Excellence',
       'Cedar Grove High School', 'Redan High School',
       'Lithonia High School', 'Stone Mountain High School',
       'Dekalb Early College Academy', 'DeKalb School of the Arts',
       'Stephenson High School',
       'Arabia Mountain High School - Academy of Engineering, Medicine and Environm',
       'Elizabeth Andrews High School',
       'DeKalb High School of Technology-South', 'Tucker High School',
       'Columbia High School', 'Druid Hills High School',
       'McNair High School', 'Clarkston High School',
       'Cross Keys High School', 'Towers High School',
       'Chamblee Charter High School', 'Dunwoody High School',
       'Southwest DeKalb High School', 'Dodge County High School',
       'Dooly County High School', 'Albany High School',
       'Monroe High School', 'Dougherty Comprehensive High School',
       'Westover High School', 'Chapel Hill High School',
       'Lithia Springs Comprehensive High School',
       'Alexander High School', 'New Manchester High School',
       'Douglas County High School', 'Early County High School',
       'Echols County High School', 'South Effingham High School',
       'Effingham County High School', 'Elbert County High School',
       'Swainsboro High School', 'Emanuel County Institute',
       'Claxton High School', 'Fannin County High School',
       'Whitewater High School', 'McIntosh High School',
       'Sandy Creek High School', 'Starrs Mill High School',
       'Fayette County High School', 'Pepperell High School',
       'Model High', 'Armuchee High School', 'Coosa High School',
       'West Forsyth High School', 'South Forsyth High School',
       'North Forsyth High School', 'Lambert High School',
       'Forsyth Academy', 'Forsyth Virtual Academy',
       'Forsyth Central High School', 'Franklin County High School',
       'Milton High School', 'Hapeville Charter Career Academy',
       'Cambridge High School', 'Banneker High School',
       'Roswell High School', 'Centennial High School',
       'Northview High School', 'Alpharetta High School',
       'Creekside High School', 'McClarin High School',
       'Independence High School', 'Chattahoochee High School',
       'Taylor Road Middle School', 'Tri-Cities High School',
       'Johns Creek High School', 'Langston Hughes High School',
       'Riverwood International Charter School',
       'North Springs High School', 'Westlake High School',
       'Gilmer High School', 'Glascock County Consolidated School',
       'Brunswick High School', 'Glynn Academy',
       'Sonoraville High School', 'Gordon Central High School',
       'Cairo High School', 'Greene County High School',
       'Grayson High School', 'Norcross High School',
       'Mill Creek High School', 'Parkview High School',
       'Brookwood High School', 'Shiloh High School',
       'Meadowcreek High School', 'Phoenix High School',
       'Collins Hill High School', 'Peachtree Ridge High School',
       'Lanier High School',
       'Gwinnett School of Mathematics, Science and Technology',
       'Berkmar High School', 'Gwinnett Online Campus',
       'Mountain View High School', 'Archer High School',
       'Discovery High School', 'South Gwinnett High School',
       'Central Gwinnett High School', 'Dacula High School',
       'North Gwinnett High School', 'Duluth High School',
       'Habersham Central High School', 'Chestatee High School',
       'Lanier Career Academy', 'West Hall High School',
       'Flowery Branch High', 'East Hall High School',
       'North Hall High School', 'Hancock Central High School',
       'Haralson County High School', 'Harris County High School',
       'Hart County High School', 'Heard County High School',
       'Union Grove High', 'Luella High School', 'Dutchtown High',
       'Patrick Henry High School', 'Locust Grove High',
       'Stockbridge High School', 'Ola High School',
       'Hampton High School', "Eagle's Landing High School",
       'Henry County High School', 'Veterans High School',
       'Houston County High School', 'Perry High School',
       'Northside High School', 'Warner Robins High School',
       'Irwin County High School',
       'East Jackson Comprehensive High School',
       'Jackson County High School', 'Jasper County High School',
       'Jeff Davis High School', 'Jefferson County High School',
       'Jenkins County High School', 'Johnson County High School',
       'Jones County High School', 'Lamar County High School',
       'Lanier County High School', 'West Laurens High School',
       'East Laurens High School', 'Lee County High School',
       'Bradwell Institute', 'Liberty County High School',
       'Lincoln County High School', 'Long County High School',
       'Lowndes High School', 'Lumpkin County High School',
       'Macon County High School', 'Madison County High School',
       'Marion County Middle/High School', 'Thomson High School',
       'McIntosh Academy', 'Greenville High School',
       'Manchester High School', 'Miller County High School',
       'Baconton Community Charter School', 'Mitchell County High School',
       'Mary Persons High School', 'Montgomery County High School',
       'Morgan County High School', 'Pleasant Valley Innovative School',
       'North Murray High School', 'Murray County High School',
       'Early College Academy of Columbus at Waverly Terrace',
       'Shaw High School', 'Spencer High School', 'Kendrick High School',
       'Hardaway High School', 'Columbus High School',
       'Carver High School', 'Jordan Vocational High School',
       'Newton High School', 'Alcovy High School', 'Eastside High School',
       'North Oconee High School', 'Oconee County High School',
       'Oglethorpe County High School', 'Hiram High School',
       'South Paulding High School', 'North Paulding High School',
       'East Paulding High School', 'Paulding County High School',
       'Peach County High School', 'Pickens County High School',
       'Pierce County High School', 'Pike County High School',
       'Rockmart High School', 'Cedartown High School',
       'Hawkinsville High School', 'Putnam County High School',
       'Quitman County High School', 'Rabun County High School',
       'Randolph Clay High School', 'Cross Creek High School',
       'Butler High School', 'Hephzibah High School',
       'Glenn Hills High School', 'Johnson Magnet', 'Josey High School',
       'Academy of Richmond County High School', 'Davidson Magnet School',
       'Laney High School', 'Z_Rockdale Career Academy',
       'Salem High School', 'Rockdale County High School',
       'Schley Middle High School', 'Screven County High School',
       'Seminole County Middle/High School', 'Spalding High School',
       'Griffin High School', 'AZ Kelsey Academy',
       'Stephens County High School', 'Stewart County High School',
       'Americus Sumter High School (Old Americus-Sumter HS S)',
       'Central Elementary/High School', 'Taliaferro County School',
       'Tattnall County High School', 'Taylor County High School',
       'Telfair County High School', 'Terrell High School',
       'Bishop Hall Charter School', 'Thomas County Central High School',
       'Northeast Campus, Tift County High School',
       'Toombs County High School', 'Towns County High School',
       'Treutlen Middle/High School', 'Callaway High School',
       'Troup County High School', 'LaGrange High School',
       'Turner County Specialty School', 'Twiggs County High School',
       'Union County High School', 'Upson-Lee High School',
       'Ridgeland High School', 'LaFayette High School',
       'Walnut Grove High School', 'Loganville High School',
       'Monroe Area High School', 'Ware County High School',
       'Warren County High School', 'Washington County High School',
       'Wayne County High School', 'Webster County High School',
       'Wheeler County High School', 'White County High School',
       'Coahulla Creek High School',
       'Northwest Whitfield County High School',
       'Southeast Whitfield County High School',
       'Wilcox County High School',
       'Washington-Wilkes Comprehensive High School',
       'Wilkinson County High School', 'Worth County High School',
       'Early College High School at Carver',
       'South Atlanta School of Health and Medical Science',
       'The Best Academy High School at Benjamin S. Carson',
       "Old Coretta Scott King Young Women's Academy High School",
       'Mays High School', 'Maynard H. Jackson, Jr. High School',
       'North Atlanta High School', 'KIPP Atlanta Collegiate',
       'School of Technology at Carver',
       'Booker T. Washington High School',
       'School of Health Sciences and Research at Carver',
       'The School of the Arts at Carver',
       'Charles Drew Charter School JA/SA',
       'Therrell School of Health and Science - C',
       'Douglass High School', 'Grady High School', 'West End Academy',
       'Bremen High School', 'Buford High School', 'Calhoun High School',
       'Carrollton High School', 'Cartersville High School',
       'Gordon Lee High School', 'Commerce High School',
       'Morris Innovative High School', 'Dalton High School',
       'Decatur High School', 'Dublin High School',
       'Gainesville High School', 'Jefferson High School',
       'Marietta High School', 'Mountain Education Center School',
       'Provost Academy Georgia', 'Georgia Connections Academy',
       'Foothills Charter High School (Madison Campus)', 'CCAT School',
       'Fulton Leadership Academy', 'Pelham High School',
       'Rome High School', 'Social Circle High School',
       'Thomasville High School', 'Trion High School',
       'Valdosta High School', 'Vidalia Comprehensive High School',
       'Georgia Academy for the Blind'], dtype=object)

In [4]:
#Saw the "Subgroup Description" column and wanted to verify all rows in data accounted for "All Students"
data_SAT["SUBGRP_DESC"].nunique()

1

In [5]:
# See only columns of interest
clean_data_SAT = data_SAT[["SCHOOL_DISTRCT_CD", "SCHOOL_DSTRCT_NM", "TEST_CMPNT_TYP_CD", "STATE_AVG_SCORE_VAL", "DSTRCT_AVG_SCORE_VAL"]]
clean_data_SAT.head(20)

,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,TEST_CMPNT_TYP_CD,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL
0,601,Appling County,Combined Test Score,1052,1020.0
1,601,Appling County,Essay Analysis Score - New,4,3.0
2,601,Appling County,Essay Reading Score - New,5,5.0
3,601,Appling County,Essay Total,13,12.0
4,601,Appling County,Essay Writing Score - New,5,5.0
5,601,Appling County,Evidence Based Reading and Writing - New,536,515.0
6,601,Appling County,Math Section Score - New,516,505.0
7,601,Appling County,Reading Test Score - New,270,258.0
8,601,Appling County,WritLang Test Score - New,266,257.0
9,602,Atkinson County,Combined Test Score,1052,994.0
10,602,Atkinson County,Essay Analysis Score - New,4,3.0
11,602,Atkinson County,Essay Reading Score - New,5,4.0
12,602,Atkinson County,Essay Total,13,12.0
13,602,Atkinson County,Essay Writing Score - New,5,5.0
14,602,Atkinson County,Evidence Based Reading and Writing - New,536,503.0
15,602,Atkinson County,Math Section Score - New,516,491.0
16,602,Atkinson County,Reading Test Score - New,270,254.0
17,602,Atkinson County,WritLang Test Score - New,266,249.0
18,603,Bacon County,Combined Test Score,1052,972.0
19,603,Bacon County,Essay Analysis Score - New,4,3.0

In [6]:
# cleaner_data_SAT = clean_data_SAT.loc[(clean_data_SAT["TEST_CMPNT_TYP_CD"] == "Combined Test Score") |  
#                                     (clean_data_SAT["TEST_CMPNT_TYP_CD"] == "Math Section Score - New") |
#                                     (clean_data_SAT["TEST_CMPNT_TYP_CD"] == "Evidence Based Reading and Writing - New"), :]

# The team decided to only look at "Combined Test Score"
cleaner_data_SAT = clean_data_SAT.loc[(clean_data_SAT["TEST_CMPNT_TYP_CD"] == "Combined Test Score"), :]

cleaner_data_SAT

,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,TEST_CMPNT_TYP_CD,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL
0,601,Appling County,Combined Test Score,1052,1020.0
9,602,Atkinson County,Combined Test Score,1052,994.0
18,603,Bacon County,Combined Test Score,1052,972.0
27,604,Baker County,Combined Test Score,1052,900.0
32,605,Baldwin County,Combined Test Score,1052,944.0
...,...,...,...,...,...
3775,789,Thomasville City,Combined Test Score,1052,1095.0
3784,791,Trion City,Combined Test Score,1052,1080.0
3793,792,Valdosta City,Combined Test Score,1052,982.0
3802,793,Vidalia City,Combined Test Score,1052,1047.0
3811,7991894,State Schools- Georgia Academy for the Blind,Combined Test Score,1052,NaN

In [7]:
# Find Standard Deviation for all District Combined Test Score values
comb_score_std = cleaner_data_SAT.groupby(["TEST_CMPNT_TYP_CD"])["DSTRCT_AVG_SCORE_VAL"].std()
# Convert value to integer so a range can be created when "binning"
comb_score_std = int(comb_score_std)
comb_score_std

65

In [8]:
# Store GA state avg for filtered out Combined Test Score
comb_state_avg = cleaner_data_SAT["STATE_AVG_SCORE_VAL"].max()
comb_state_avg

1052

In [9]:
# *** Couldn't make it work with bins ***

#bins = [0, (comb_state_avg - comb_score_std), (comb_state_avg + comb_score_std), 1600]
#group_labels = ["Below Average", "Average", "Average", "Above Average"]

#cleaner_data_SAT["Combined Score Bracket"] = pd.cut(cleaner_data_SAT[""])

# np.where(cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] < (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] - comb_score_std), "Below Average")

# ***

# Add a new column with bracket category based off of 1 standard deviation from district average

# Three conditions
conditions = [
    (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] < (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] - comb_score_std)),
    (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] >= (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] - comb_score_std)) & (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] <= (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] + comb_score_std)),
    (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] > (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] + comb_score_std))
             ]

# Number of values must match number of conditions
values = ["Below Average", "Average", "Above Average"]

cleaner_data_SAT["Test Score Bracket"] = np.select(conditions, values)
cleaner_data_SAT

<ipython-input-9-f51368631663>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaner_data_SAT["Test Score Bracket"] = np.select(conditions, values)

,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,TEST_CMPNT_TYP_CD,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL,Test Score Bracket
0,601,Appling County,Combined Test Score,1052,1020.0,Average
9,602,Atkinson County,Combined Test Score,1052,994.0,Average
18,603,Bacon County,Combined Test Score,1052,972.0,Below Average
27,604,Baker County,Combined Test Score,1052,900.0,Below Average
32,605,Baldwin County,Combined Test Score,1052,944.0,Below Average
...,...,...,...,...,...,...
3775,789,Thomasville City,Combined Test Score,1052,1095.0,Average
3784,791,Trion City,Combined Test Score,1052,1080.0,Average
3793,792,Valdosta City,Combined Test Score,1052,982.0,Below Average
3802,793,Vidalia City,Combined Test Score,1052,1047.0,Average
3811,7991894,State Schools- Georgia Academy for the Blind,Combined Test Score,1052,NaN,0

In [10]:
# Drop all rows with NA data
cleaner_data_SAT = cleaner_data_SAT.dropna()
cleaner_data_SAT

,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,TEST_CMPNT_TYP_CD,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL,Test Score Bracket
0,601,Appling County,Combined Test Score,1052,1020.0,Average
9,602,Atkinson County,Combined Test Score,1052,994.0,Average
18,603,Bacon County,Combined Test Score,1052,972.0,Below Average
27,604,Baker County,Combined Test Score,1052,900.0,Below Average
32,605,Baldwin County,Combined Test Score,1052,944.0,Below Average
...,...,...,...,...,...,...
3766,786,Social Circle City,Combined Test Score,1052,1050.0,Average
3775,789,Thomasville City,Combined Test Score,1052,1095.0,Average
3784,791,Trion City,Combined Test Score,1052,1080.0,Average
3793,792,Valdosta City,Combined Test Score,1052,982.0,Below Average
3802,793,Vidalia City,Combined Test Score,1052,1047.0,Average

In [15]:
# Rename columns
cleaner_data_SAT = cleaner_data_SAT.rename(columns = 
                        {"SCHOOL_DISTRCT_CD": "School Dist Code",
                         "SCHOOL_DSTRCT_NM": "School Dist Name",
                         "TEST_CMPNT_TYP_CD": "Test Component",
                         "STATE_AVG_SCORE_VAL": "State Avg Score",
                         "DSTRCT_AVG_SCORE_VAL": "Dist Avg Score"
                        }) 
cleaner_data_SAT

,School Dist Code,School Dist Name,Test Component,State Avg Score,Dist Avg Score,Test Score Bracket
0,601,Appling County,Combined Test Score,1052,1020.0,Average
9,602,Atkinson County,Combined Test Score,1052,994.0,Average
18,603,Bacon County,Combined Test Score,1052,972.0,Below Average
27,604,Baker County,Combined Test Score,1052,900.0,Below Average
32,605,Baldwin County,Combined Test Score,1052,944.0,Below Average
...,...,...,...,...,...,...
3766,786,Social Circle City,Combined Test Score,1052,1050.0,Average
3775,789,Thomasville City,Combined Test Score,1052,1095.0,Average
3784,791,Trion City,Combined Test Score,1052,1080.0,Average
3793,792,Valdosta City,Combined Test Score,1052,982.0,Below Average
3802,793,Vidalia City,Combined Test Score,1052,1047.0,Average

In [16]:
# Saved cleaned data as CSV file
cleaner_data_SAT.to_csv("cleaner_data_SAT.csv", index = False)