In [48]:
# Dependencies and setup
import pandas as pd
import numpy as np

# Load data files
raw_data_SAT = "GOSA_SAT_highest_2018.csv"

# Read School and Student data files and store them each into Pandas DataFrames
data_SAT = pd.read_csv(raw_data_SAT)

# Combine the data into a single dataset
#school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

data_SAT.head()

,LONG_SCHOOL_YEAR,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,INSTN_NUMBER,INSTN_NAME,SUBGRP_DESC,TEST_CMPNT_TYP_CD,NATIONAL_NUM_TESTED_CNT,STATE_NUM_TESTED_CNT,DSTRCT_NUM_TESTED_CNT,INSTN_NUM_TESTED_CNT,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL,INSTN_AVG_SCORE_VAL
0,2017-18,601,Appling County,103,Appling County High School,All Students,Combined Test Score,2136539,65795,102.0,102.0,1052,1020.0,1020.0
1,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Analysis Score - New,1449142,28569,29.0,29.0,4,3.0,3.0
2,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Reading Score - New,1449142,28569,29.0,29.0,5,5.0,5.0
3,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Total,1449142,28569,29.0,29.0,13,12.0,12.0
4,2017-18,601,Appling County,103,Appling County High School,All Students,Essay Writing Score - New,1449142,28569,29.0,29.0,5,5.0,5.0

In [20]:
#data_SAT["SCHOOL_DSTRCT_NM"].unique()

In [21]:
#data_SAT["INSTN_NAME"].unique()

In [18]:
#Saw the "Subgroup Description" column and wanted to verify all rows in data accounted for "All Students"
data_SAT["SUBGRP_DESC"].nunique()

1

In [49]:
clean_data_SAT = data_SAT[["SCHOOL_DISTRCT_CD", "SCHOOL_DSTRCT_NM", "TEST_CMPNT_TYP_CD", "STATE_AVG_SCORE_VAL", "DSTRCT_AVG_SCORE_VAL"]]
clean_data_SAT.head(20)

,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,TEST_CMPNT_TYP_CD,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL
0,601,Appling County,Combined Test Score,1052,1020.0
1,601,Appling County,Essay Analysis Score - New,4,3.0
2,601,Appling County,Essay Reading Score - New,5,5.0
3,601,Appling County,Essay Total,13,12.0
4,601,Appling County,Essay Writing Score - New,5,5.0
5,601,Appling County,Evidence Based Reading and Writing - New,536,515.0
6,601,Appling County,Math Section Score - New,516,505.0
7,601,Appling County,Reading Test Score - New,270,258.0
8,601,Appling County,WritLang Test Score - New,266,257.0
9,602,Atkinson County,Combined Test Score,1052,994.0
10,602,Atkinson County,Essay Analysis Score - New,4,3.0
11,602,Atkinson County,Essay Reading Score - New,5,4.0
12,602,Atkinson County,Essay Total,13,12.0
13,602,Atkinson County,Essay Writing Score - New,5,5.0
14,602,Atkinson County,Evidence Based Reading and Writing - New,536,503.0
15,602,Atkinson County,Math Section Score - New,516,491.0
16,602,Atkinson County,Reading Test Score - New,270,254.0
17,602,Atkinson County,WritLang Test Score - New,266,249.0
18,603,Bacon County,Combined Test Score,1052,972.0
19,603,Bacon County,Essay Analysis Score - New,4,3.0

In [50]:
cleaner_data_SAT = clean_data_SAT.loc[(clean_data_SAT["TEST_CMPNT_TYP_CD"] == "Combined Test Score") |  
                                    (clean_data_SAT["TEST_CMPNT_TYP_CD"] == "Math Section Score - New") |
                                    (clean_data_SAT["TEST_CMPNT_TYP_CD"] == "Reading Test  Score - New"), :]


cleaner_data_SAT

# cleaner_data_SAT = clean_data_SAT[clean_data_SAT["TEST_CMPNT_TYP_CD"].isin(["Math Section Score - New"])]

# cleaner_data_SAT

,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,TEST_CMPNT_TYP_CD,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL
0,601,Appling County,Combined Test Score,1052,1020.0
6,601,Appling County,Math Section Score - New,516,505.0
7,601,Appling County,Reading Test Score - New,270,258.0
9,602,Atkinson County,Combined Test Score,1052,994.0
15,602,Atkinson County,Math Section Score - New,516,491.0
...,...,...,...,...,...
3808,793,Vidalia City,Math Section Score - New,516,516.0
3809,793,Vidalia City,Reading Test Score - New,270,266.0
3811,7991894,State Schools- Georgia Academy for the Blind,Combined Test Score,1052,NaN
3813,7991894,State Schools- Georgia Academy for the Blind,Math Section Score - New,516,NaN
3814,7991894,State Schools- Georgia Academy for the Blind,Reading Test Score - New,270,NaN

In [54]:
comb_state_avg = 1052
buffer = 50

bins = [0, (comb_state_avg-buffer), (comb_state_avg+buffer), 1600]
group_labels = ["Below Average", "Average", "Average", "Above Average"]

cleaner_data_SAT["Combined Score Bracket"] = pd.cut(cleaner_data_SAT[""])

# np.where(cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] < (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] - buffer), "Below Average")

# ***

conditions = [
    (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] < (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] - buffer)),
    (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] >= (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] - buffer)) & (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] <= (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] + buffer)),
    (cleaner_data_SAT["DSTRCT_AVG_SCORE_VAL"] > (cleaner_data_SAT["STATE_AVG_SCORE_VAL"] + buffer))
             ]

values = ["Below Average", "Average", "Above Average"]

cleaner_data_SAT["Bracket"] = np.select(conditions, values)
cleaner_data_SAT

<ipython-input-54-da546c01deee>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaner_data_SAT["Bracket"] = np.select(conditions, values)

,SCHOOL_DISTRCT_CD,SCHOOL_DSTRCT_NM,TEST_CMPNT_TYP_CD,STATE_AVG_SCORE_VAL,DSTRCT_AVG_SCORE_VAL,Bracket
0,601,Appling County,Combined Test Score,1052,1020.0,Average
6,601,Appling County,Math Section Score - New,516,505.0,Average
7,601,Appling County,Reading Test Score - New,270,258.0,Average
9,602,Atkinson County,Combined Test Score,1052,994.0,Below Average
15,602,Atkinson County,Math Section Score - New,516,491.0,Average
...,...,...,...,...,...,...
3808,793,Vidalia City,Math Section Score - New,516,516.0,Average
3809,793,Vidalia City,Reading Test Score - New,270,266.0,Average
3811,7991894,State Schools- Georgia Academy for the Blind,Combined Test Score,1052,NaN,0
3813,7991894,State Schools- Georgia Academy for the Blind,Math Section Score - New,516,NaN,0
3814,7991894,State Schools- Georgia Academy for the Blind,Reading Test Score - New,270,NaN,0